name: Knip Reporter

on:
  pull_request:
    branches: [ main, master ]

jobs:
  knip:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Report Knip Results
        uses: codex-/knip-reporter@v3